# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '使用kissxml解析xml' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 使用kissxml解析xml
pod 'KissXML', '~> 5.1.2'
end
